version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: moodshare-mysql    environment:
      MYSQL_ROOT_PASSWORD: @Aa527913025
      MYSQL_DATABASE: moodshare
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: moodshare-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    container_name: moodshare-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/moodshare?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: MySecurePassword123!
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  mysql_data:
